name: bci_management_system
description: BCI integrated student management and payroll Flutter MVP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
